### ISSUE TITLE
Sidekiq Driver

### ISSUE THREAD

**Issue by jonsgreen** [taskrabbit/resque-bus#10]
We are considering using Sidekiq as a message bus. In your blogpost on resque-bus you mention the idea of using Sidekiq as a driver. Anymore thoughts on that?
I have not explored your codebase yet but I am curious if you think it might be easily adaptable? Would you be interested in pull requests?

**Comment by jonsgreen** [comment]
I have been playing a bit with adapting for Sidekiq and have a spike [here](https://github.com/jonsgreen/resque-bus/tree/sidekiq-adapter). It is a pretty rough proof of concept at the moment but it did confirm that the data stored in Redis is compatible for Sidekiq. 

I have some questions about taking this further:

1. What is the best way to handle gem requirement. Although you are open to abandoning Resque altogether I would be concerned that Sidekiq is not appropriate for every project. Both gems could be installed and required only on demand. Are there other options to consider?
2. I did not fully adopt an adapter pattern but rather just included conditionally what was required to adapt for Sidekiq. I would be open to refactoring this more and would be open to suggestions as to the cleanest way to hook this up. I am thinking it could be part of the initialization process that for example could set a driver and rider that then would get used in the following:

        enqueue_to(incoming_queue, ResqueBus.driver, to_publish)
Is that the sort of thing you had in mind?
3. There are some features that I still have not touched like heartbeat. I probably should also make an encoder class that adapts for Resque and Sidekiq accordingly even though the data seems to work fine. I believe that Sidekiq incorporates retries automatically by default. I could not find where the critical queuing is implemented in the code? Is that feature currently active? Obviously specs are in order as well. Are there any other features that I should be concerned about?
4. I made some changes to the rake tasks. In particular I am executing the resque:work and sidekiq commands internally. The main motivation for this was to be able to dynamically set the queues for Sidekiq. It might make more sense to just output the queues and allow users to configure and turn on their background processors themselves like it is done currently. 
5. One feature that is lost with the current implementation for Sidekiq is that a job id (jid) does not get set since you are bypassing the standard API (perform_async) and storing in Redis directly. I am curious why you chose this approach for Resque. It seems like there is the risk of something changing in the data structure over time and being locked to older versions of these gems. Of course the public API could change as well (I believe it already has changed or is changing for Resque). There may be certain accounting and monitoring functionality that would be lost without the jid. Any thoughts?
6. I noticed that there is some switching back and forth between Resque and original redis instances in the code. Can you explain the reason for this a bit more to me? 
7. What do you think of the busline naming idea and implementation. I was trying to follow the domain metaphor pattern already present in the gem. I am open to other ideas.
8. One of the trickier things that I had to figure out along the way was that the resque namespace was obscuring the queues for Sidekiq. For now I just commented out the default namespace but it should be configurable as well. 
9. Are there any other aspects of the code or gotchas that I should be looking out for with this feature? 

Thanks again for this great gem and for your openness to and support of the Sidekiq adapter idea. I have enjoyed exploring and getting to know the code base so far. Please feel free to offer any general or specific feedback and any answers to the above questions are greatly appreciated.

**Comment by bleonard** [comment]
Thanks for the investigation @jonsgreen !
It does look fairly straightforward assuming your code is working in Sidekiq as expected.

1. The three main options for supporting Sidekiq (and probably delayed_job) would be:
a) one "core" gem -- maybe something like `queue-bus` and then adapter gems like `queue-bus-sidekiq` etc.
b) more or less the same adapter pattern as that would be (probably would define the Driver class in each) but all in the same gem.
c) dynamic injection along the lines of what you have here

the first one seems a little premature. I'd be open to b or c. I think c might get a little confusing and there might be conflicts.

2. There really are just a few cases here in addition the defining of the the `Driver` and `Rider`
`enqueue`: how does resque, sidekiq, delayed_job put something in the incoming queue
`set_queues`: done in the rake job (for Resque it is setting the ENV["QUEUES"])
`enable!`: called when consuming app set this to be the system in use.

maybe some heartbeat stuff if we tackle that one.
maybe some callbacks in the Driver, etc.

I'd probably wrap up these differences in a class for each queue system. You called it busline but we could just call it adapter. My current opinion is to be less cute than I was when I wrote this :-)

So then we it set the adapter it would load that class and call `enable!`
This might require resque or sidekiq, etc.
I think we can probably figure out some compatible version of the Driver, Rider, and Subscriber. Then this call might inject some other business in them (add in Sidekiq::Worker).

When someone calls `publish` we'd relay that to the current adapter.
Stuff like that.

3. Retry is handled in the resque-retry gem now in general. 

The heartbeat code doesn't really need anything Resque specific, but it does need redis. We could abstract that. Resque-scheduler is used to make it run every minute.

4. We don't really use resque:work
What we'd really need to update is `resquebus:setup` -- that's what would tell Sidekiq what queues to run. It's easy because Resque checks and ENV variable. Does Sidekiq do something like that.

Then you'd run `rake resquebus:setup sidekiq` or something like that.
FYI: If you just run the setup command, it prints out the queues.

5. I did know that the gem was changing but not the data structure. I just went straight to redis to not mess with and side effects as i recall. My idea was that this system was more self-contained and not affect "regular" Redis. So if you had some callback set on queueing everything, this wouldn't use it. I can't say if that was a good or bad idea.

Either way, if we had the adapter scheme like I mentioned, that could do whatever it wanted.

6. The switching was to allow the bus and "regular" Resque to exist in two different Redis databases. That's how we ran it originally and it had some value. But it's important to set it back because the code that's running in the subscription might enqueue something in "regular" Resque.

7. I'd probably go with `adapter` in this case as noted.

8. I forget what that's about, but separating the enqueing code would allow it to be more normal for that system.

9. Not that I can think or at the moment. Maybe the server UI piece. That would be helpful if there is an equivalent for Sidekiq UI.

I'd be willing to do a refactor towards a Resque adapter along the lines I've talked about and leave it clear where the hooks would be to create a Sidekiq adapter if you are interested.

**Comment by jonsgreen** [comment]
I like your idea of refactoring to support a Resque adapter since that would setup the design pattern as you intend it to be. Let me know when you think you might have time to work on that. 

There are two ways I know of to specify the queues for Sidekiq. One is when you start the sidekiq workers:
  
    bundle exec sidekiq -q resquebus -q some_other_queue

Or you can do it as a list in a sidekiq.yml file. I don't think that it can be read from an environment variable but I could be wrong.

I found that the Sidekiq UI did pick up the processors, queues and jobs (even without the jids) and just mixed them in with whatever other Sidekiq instances I had running. If we wanted to have a distinct tab I could look into what that entails since I bet the Sidekiq API and web allows for that.

**Comment by bleonard** [comment]
This gem adds a list of the current subscriptions and allows removal of them in the Resque UI. Tha'ts what I was talking about wrt the UI.

**Comment by bleonard** [comment]
I can start a refactor branch next week. Does that work for you @jonsgreen ?

**Comment by bleonard** [comment]
@jonsgreen I created PR https://github.com/taskrabbit/resque-bus/pull/13. can you branch off of that and see how it goes from there.

**Comment by jonsgreen** [comment]
@bleonard: sorry I was sending notifications to a wrong email address. 

Thanks for setting this up! I will try to dig into it this week.

**Comment by bleonard** [comment]
ok @jonsgreen I've moved this to new projects!
closing this down in favor of using the new repo.

https://github.com/queue-bus
You should have access to change the base and sidekiq projects.
can you try out the master branch of https://github.com/queue-bus/sidekiq-bus and let me know if it's still working as expected. If not make an issue over there.

Overall, I'll be retiring this repo in favor of the new one.
