### ISSUE TITLE
How to use this in Rails app

### ISSUE THREAD

**Issue by ghost** [taskrabbit/resque-bus#12]
I wan to know how to use the resque-bus in my Rails app.what's the steps?

**Comment by rtcoms** [comment]
I am going ti need lots of subscribers in my app. Putting all of those in initializers folder, doesn't feel like a good practice. Most probably those subscriber will have active_recrod queries , and those also should not be in intializers.

What would you recommend ?

I want  to have a subscribers folders inside app folder . is it possible to have something like that ?

**Comment by bleonard** [comment]
@rtcoms There seem to be two options.

A) put the subscriptions in an initializer, but each one only has one line - something like this...
```ruby
subscribe "some_event" do |attributes|
  SomeClass.process(id: attributes['user_id'])
end
```
That will keep it simple. And make the code easier to test.

B) make a `subscribers` folder that has lots of classes that use `ResqueBus::Subscriber` module as described in the readme.
Just be sure to require all the files in that folder on startup (maybe in an initializer). This might work in production without that, but will not work in development because of lazy loading differences.

In an app that _only_ has tons of subscriptions, we are using B. In a regular app with fewer subscriptions, we are using A, but always keeping the "action" to one line or so.
